# Generated by Django 5.2.7 on 2025-10-25 20:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaterialJoya",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TipoJoya",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Orden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_orden",
                    models.PositiveIntegerField(editable=False, unique=True),
                ),
                (
                    "tipo_certificado",
                    models.CharField(
                        choices=[
                            ("Verbal", "Verbal"),
                            ("Gem Card", "Gem Card"),
                            ("Escrito", "Escrito"),
                            ("Reimpresion", "Reimpresión"),
                            (
                                "Verbal a Gem Card o Escrito",
                                "Verbal a Gem Card o Escrito",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("color_gema", models.CharField(max_length=100)),
                ("peso", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tiene_seguro", models.BooleanField(default=False)),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_entrega_sugerida", models.DateTimeField()),
                ("tags", models.TextField(blank=True)),
                (
                    "material_joya",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="certificacion.materialjoya",
                    ),
                ),
                (
                    "tipo_joya",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="certificacion.tipojoya",
                    ),
                ),
            ],
        ),
    ]
