# Generated by Django 5.2.7 on 2025-10-25 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificacion", "0002_auto_20251025_2031"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_certificado",
                    models.CharField(
                        choices=[
                            ("Verbal", "Verbal"),
                            ("Gem Card", "Gem Card"),
                            ("Escrito", "Escrito"),
                            ("Reimpresion", "Reimpresión"),
                            (
                                "Verbal a Gem Card o Escrito",
                                "Verbal a Gem Card o Escrito",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "tipo_item",
                    models.CharField(
                        choices=[
                            ("Piedras sueltas", "Piedras sueltas"),
                            ("Lote de gemas", "Lote de gemas"),
                            ("Joya", "Joya"),
                            ("Set de joyas", "Set de joyas"),
                        ],
                        max_length=50,
                    ),
                ),
                ("color_gema", models.CharField(blank=True, max_length=100)),
                (
                    "peso",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(blank=True, null=True)),
                ("cantidad_total", models.PositiveIntegerField(blank=True, null=True)),
                ("tipo_gema", models.CharField(blank=True, max_length=100)),
                (
                    "peso_promedio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "material_joya",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="certificacion.materialjoya",
                    ),
                ),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="certificacion.orden",
                    ),
                ),
                (
                    "tipo_joya",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="certificacion.tipojoya",
                    ),
                ),
                (
                    "tipos_joya",
                    models.ManyToManyField(
                        blank=True,
                        related_name="items_set",
                        to="certificacion.tipojoya",
                    ),
                ),
            ],
        ),
    ]
