# Generated by Django 5.2.7 on 2025-10-25 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("certificacion", "0003_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orden",
            name="color_gema",
        ),
        migrations.RemoveField(
            model_name="orden",
            name="material_joya",
        ),
        migrations.RemoveField(
            model_name="orden",
            name="peso",
        ),
        migrations.RemoveField(
            model_name="orden",
            name="tipo_certificado",
        ),
        migrations.RemoveField(
            model_name="orden",
            name="tipo_joya",
        ),
    ]
