# Generated by Django 5.2.7 on 2025-10-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificacion", "0005_auto_20251025_2149"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="tiene_seguro",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="orden",
            name="numero_orden",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
