# Generated by Django 5.2.7 on 2025-10-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificacion", "0006_item_tiene_seguro_alter_orden_numero_orden"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="tags",
            field=models.TextField(blank=True),
        ),
    ]
