# Generated by Django 5.2.7 on 2025-10-25 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("certificacion", "0007_item_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orden",
            name="tiene_seguro",
        ),
    ]
