# Generated by Django 5.2.7 on 2025-10-25 22:23

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('certificacion', '0008_remove_orden_tiene_seguro'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
